# permissions for end users to view bars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bar-viewer-role
rules:
- apiGroups:
  - test.example.org
  resources:
  - bars
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.example.org
  resources:
  - bars/status
  verbs:
  - get
